name: iosApp
options:
  bundleIdPrefix: com.xndev
  deploymentTarget:
    iOS: "15.0"
  createIntermediateGroups: true

targets:
  iosApp:
    type: application
    platform: iOS
    sources:
      - path: iosApp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.xndev.retroAdventure
        PRODUCT_NAME: RetroAdventure
        DEVELOPMENT_TEAM: A69JRS6V57
        CODE_SIGN_STYLE: Automatic
        INFOPLIST_FILE: iosApp/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "1,2"
        ENABLE_USER_SCRIPT_SANDBOXING: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        FRAMEWORK_SEARCH_PATHS:
          - $(inherited)
          - $(SRCROOT)/../app/build/xcode-frameworks/$(CONFIGURATION)/$(SDK_NAME)
        OTHER_LDFLAGS:
          - $(inherited)
          - -framework
          - ComposeApp
    preBuildScripts:
      - name: Compile Kotlin Framework
        basedOnDependencyAnalysis: false
        script: |
          if [ "YES" = "$OVERRIDE_KOTLIN_BUILD_IDE_SUPPORTED" ]; then
            echo "Skipping Gradle build task (OVERRIDE_KOTLIN_BUILD_IDE_SUPPORTED=YES)"
            exit 0
          fi
          cd "$SRCROOT/.."
          ./gradlew :app:embedAndSignAppleFrameworkForXcode

schemes:
  iosApp:
    build:
      targets:
        iosApp: all
    run:
      config: Debug
