package com.xndev.retroadventure.engine

import java.io.File
import kotlin.test.Test
import kotlin.test.assertTrue

/**
 * The regression suite: replay upstream's own test scripts through this engine
 * and diff the transcript against upstream's recorded output.
 *
 * vendor/open-adventure/tests holds 107 .log/.chk pairs. A .log is a script of
 * keystrokes; the matching .chk is exactly what upstream's `advent` printed when
 * fed it, byte for byte. Nearly every one begins with `seed NNNN`, which pins
 * the LCG, so the whole run is deterministic and a diff is a real verdict rather
 * than a judgment call.
 *
 * Four of the 107 (cheatresume, cheatresume2, resumefail2, savetamper) need
 * savegame files generated by upstream's `cheat` binary and are skipped; the
 * reference C binary fails them here too for the same reason, so 103 is the
 * ceiling, not 107. See SKIPPED below.
 *
 * This test does NOT fail the build on a transcript mismatch while the port is
 * incomplete -- it would fail on all of them and tell you nothing you didn't
 * already know. It fails only when the score goes *down*, and always prints the
 * scoreboard plus the first diverging line of each failure, which is the next
 * thing to work on. Raise the baselines as verbs land, so the suite ratchets.
 */
class TranscriptTest {

    private val testDir = File(
        System.getProperty("retroadventure.testdir")
            ?: error("retroadventure.testdir not set; see engine/build.gradle.kts")
    )

    /** Need savegame files from upstream's `cheat` binary, which we do not build. */
    private val skipped = setOf("cheatresume", "cheatresume2", "resumefail2", "savetamper")

    /**
     * The ratchet. Raise both as the port advances -- that is the whole point
     * of this file: it makes "did I break something" a question the build can
     * answer rather than a thing you notice three commits later.
     *
     * While no transcript yet passes end to end, `passBaseline` alone would be
     * a dead ratchet stuck at zero for a long time. `lineBaseline` counts the
     * matching prefix of every transcript, so porting one more verb moves a
     * number today and a regression shows up immediately.
     */
    private val passBaseline = 0
    private val lineBaseline = 23000

    private fun runScript(log: File): String {
        val lines = log.readLines().iterator()
        val out = Output()
        val adv = Adventure(input = { if (lines.hasNext()) lines.next() else null }, out = out)
        // Upstream seeds from the clock and then most scripts immediately issue
        // their own `seed` command; any fixed value works as the pre-seed.
        adv.run(1)
        return out.toString()
    }

    @Test
    fun transcripts() {
        val logs = testDir.listFiles { f -> f.name.endsWith(".log") }
            ?.sortedBy { it.name }
            ?: error("no test scripts under $testDir")

        assertTrue(logs.size >= 100, "expected ~107 transcripts, found ${logs.size}")

        var passed = 0
        var matchedLines = 0
        var expectedLines = 0
        val failures = mutableListOf<String>()
        val blockers = mutableMapOf<String, MutableList<String>>()

        for (log in logs) {
            val name = log.name.removeSuffix(".log")
            if (name in skipped) continue
            val chk = File(testDir, "$name.chk")
            if (!chk.exists()) continue

            val actual = try {
                runScript(log)
            } catch (e: Throwable) {
                failures += "$name: threw ${e::class.simpleName}: ${e.message}"
                continue
            }
            val expected = chk.readText()

            val e = expected.lines()
            expectedLines += e.size
            matchedLines += matchingPrefix(e, actual.lines())

            if (actual == expected) {
                passed++
            } else {
                val divergence = firstDivergence(expected, actual)
                failures += "$name: $divergence"
                blockers.getOrPut(blame(divergence)) { mutableListOf() } += "$name:$divergence"
            }
        }

        val total = logs.size - skipped.size
        println("=".repeat(72))
        println("Transcript suite: $passed/$total transcripts match upstream exactly")
        println("Matching prefix:  $matchedLines/$expectedLines lines " +
            "(${matchedLines * 100 / expectedLines}%), ${skipped.size} savegame tests skipped")
        println("=".repeat(72))
        // The to-do list in priority order: what is stopping the most
        // transcripts right now. Port the top entry, re-run, repeat. The
        // "ported path" bucket is different in kind from the rest -- those are
        // bugs in code that already exists, not verbs that are missing, and
        // they are usually worth more than their count suggests.
        println("Blocking the most transcripts:")
        for ((cause, hits) in blockers.entries.sortedByDescending { it.value.size }) {
            println("  %3d  %s".format(hits.size, cause))
            hits.take(3).forEach { println("         $it") }
            if (hits.size > 3) println("         ... and ${hits.size - 3} more")
        }

        assertTrue(
            passed >= passBaseline,
            "transcript pass count fell to $passed, below the baseline of $passBaseline"
        )
        assertTrue(
            matchedLines >= lineBaseline,
            "matching-prefix lines fell to $matchedLines, below the baseline of $lineBaseline"
        )
    }

    /** Reduce a divergence message to the thing worth fixing. */
    private fun blame(divergence: String): String {
        Regex("""\[not ported yet] (verb|bare object) ([^"\s]+)""").find(divergence)?.let {
            return "${it.groupValues[1]}: ${it.groupValues[2]}"
        }
        if (divergence.startsWith("threw ")) return "crash"
        return "output mismatch (ported path)"
    }

    /** How many leading lines of the expected transcript we reproduce. */
    private fun matchingPrefix(expected: List<String>, actual: List<String>): Int {
        var n = 0
        while (n < expected.size && n < actual.size && expected[n] == actual[n]) n++
        return n
    }

    /** Report the first line where the two transcripts differ, with context. */
    private fun firstDivergence(expected: String, actual: String): String {
        val e = expected.lines()
        val a = actual.lines()
        for (i in 0 until maxOf(e.size, a.size)) {
            val el = e.getOrNull(i)
            val al = a.getOrNull(i)
            if (el != al) {
                return "line ${i + 1}: expected ${el?.let { "\"$it\"" } ?: "<end>"} " +
                    "but got ${al?.let { "\"$it\"" } ?: "<end>"}"
            }
        }
        return "identical text but different length"
    }
}
